FROM python:3.12-alpine
LABEL authors="zwickvitaly"

ENV PYTHONUNBUFFERED=1

WORKDIR /api_app

COPY requirements_api_app.txt requirements.txt

RUN pip install -r requirements.txt

COPY api_app/ .

ENTRYPOINT uvicorn app:app --host 0.0.0.0 --port 8080


